---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acs
  namespace: gitops-resources
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops-resources
  source:
    repoURL: https://github.com/redhat-appstudio/rhads-services-gitops
    targetRevision: main
    path: "components/acs"
  destination:
    namespace: rhacs-operator
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: gitops-resources
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
