apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: gitops-resources
spec:
  destination:
    namespace: jenkins
    server: https://kubernetes.default.svc
  project: gitops-resources
  sources:
    - repoURL: "https://github.com/redhat-appstudio/rhads-services-gitops.git"
      targetRevision: main
      path: "components/jenkins"
    - repoURL: https://charts.jenkins.io
      chart: jenkins
      targetRevision: 5.8.104 # Use a specific chart version
      helm:
        releaseName: jenkins
        valueFiles:
          - $values/components/jenkins/values.yaml
    - repoURL: https://github.com/redhat-appstudio/rhads-services-gitops.git
      targetRevision: main
      ref: values
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
