apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jfrog-artifactory-jcr
  namespace: gitops-resources
spec:
  destination:
    namespace: artifactory3
    server: https://kubernetes.default.svc
  project: gitops-resources
  sources:
  - repoURL: 'https://github.com/smatula/rhtap-services-gitops'
    targetRevision: artifactory
    path: 'components/artifactory'
  - repoURL: https://charts.jfrog.io
    chart: artifactory-jcr
    targetRevision: 107.117.12 # Use a specific chart version
    helm:
      releaseName: jfrog-container-registry
      valueFiles:
        - https://github.com/smatula/rhtap-services-gitops/blob/main/components/artifactory/values.yaml
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

