apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jfrog-artifactory-jcr
  namespace: gitops-resources
spec:
  destination:
    namespace: artifactory
    server: https://kubernetes.default.svc
  project: gitops-resources
  # --- NEW: Use the 'sources' field instead of 'source' ---
  sources:
  # Source 1: The raw Kubernetes manifests for the Secret and ConfigMap
  - repoURL: 'https://github.com/smatula/rhtap-services-gitops'
    targetRevision: artifactory
    path: 'components/artifactory'
  - repoURL: https://charts.jfrog.io
    chart: artifactory-jcr
    targetRevision: 107.117.8 # Use a specific chart version
    helm:
      releaseName: jfrog-container-registry
      valueFiles:
        - $values/values.yaml
  - repoURL: https://github.com/smatula/rhtap-services-gitops
    targetRevision: artifactory
    ref: values
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

