apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus
  namespace: gitops-resources
spec:
  destination:
    namespace: nexus
    server: https://kubernetes.default.svc
  project: gitops-resources
  sources:
  - repoURL: https://sonatype.github.io/helm3-charts/
    chart: nxrm-ha
    targetRevision: 84.0.0
    helm:
      releaseName: nexus-service
      valueFiles:
        - $values/components/nexus/values.yaml
  - repoURL: https://github.com/smatula/rhtap-services-gitops
    targetRevision: nexus
    ref: values
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

