apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tpa
  namespace: gitops-resources
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tssc-tpa
  project: gitops-resources
  source:
    repoURL: https://github.com/smatula/rhtap-services-gitops
    path: ./components/tpa
    targetRevision: tpa
    kustomize:
      parameters:
        - name: KEYCLOAK_HOSTNAME
          value: sso
        - name: SEED_STRING
          value: oyVHvG2cgySdlc5K
        - name: APP_DOMAIN_URL
          value: -tssc-tpa.apps.cluster-nlqdc.nlqdc.sandbox740.opentlc.com
        - name: OIDC_ISSUER_URL
          value: https://sso.apps.cluster-nlqdc.nlqdc.sandbox740.opentlc.com/realms/chicken
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
