apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tpa
  namespace: gitops-resources
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tssc-tpa
  project: gitops-resources
  source:
    repoURL: https://github.com/smatula/rhtap-services-gitops
    path: ./components/tpa
    targetRevision: tpa2
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
