apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tpa-sequential-deployment
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - name: vars-and-secrets
        app_wave: "1"
        app_path: components/tpa/vars-config
        dependencies: []
      - name: tpa
        app_wave: "2"
        app_path: components/tpa/tpa-app
        dependencies: [vars-and-secrets]
  template:
    metadata:
      name: '{{.name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{.app_wave}}' 
        argocd.argoproj.io/applicationset.dependencies: '{{.dependencies | toJson}}'
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: tssc-tpa
      project: gitops-resources
      source:
        repoURL: https://github.com/smatula/rhtap-services-gitops
        targetRevision: tpa2
        path: '{{.app_path}}'
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: openshift-gitops
        syncOptions:
          - RespectDependencies=true
          - CreateNamespace=true
          - PruneLast=true
        automated:
          prune: true
          selfHeal: true

