apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tpa-service
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster-service-app: "true"
  template:
    metadata:
      name: 'tpa'
      namespace: gitops-resources
    spec:
      project: gitops-resources
      destination:
        server: https://kubernetes.default.svc
        namespace: tssc-tpa
      source:
        repoURL: https://github.com/redhat-appstudio/rhtap-services-gitops
        path: ./components/tpa
        targetRevision: HEAD
        kustomize:
          patches:
            # Validation note: Ensure target resources meet expected structure:
            # - KeycloakRealmImport keycloak-chicken: realm.clients length >= 5, clients[4].redirectUris length >= 5
            # - Application trusted-profile-analyzer: source.helm.parameters length == 2
            - patch: |
                - op: replace
                  path: /spec/host
                  # Keycloak hostname patch
                  value: "{{ index .metadata.annotations "KChost" }}"
              target:
                kind: Route
                name: keycloak
            - patch: |
                - op: replace
                  path: /spec/hostname/hostname
                  # Keycloak hostname patch
                  value: "{{ index .metadata.annotations "KChost" }}"
              target:
                kind: Keycloak
                name: keycloak
            - patch: |
                - op: replace
                  path: /spec/realm/clients/4/redirectUris/1
                  # Ensure clients are in expected order before deploying
                  # Targets 5th client (index 4) in realm.clients; index 1 = TPA console callback URI
                  value: "{{ index .metadata.annotations "redirect1" }}"
              target:
                kind: KeycloakRealmImport
                name: keycloak-chicken
            - patch: |
                - op: replace
                  path: /spec/realm/clients/4/redirectUris/2
                  # Ensure clients are in expected order before deploying
                  # Targets 5th client (index 4) in realm.clients; index 2 = TPA console callback URI with wildcard
                  value: "{{ index .metadata.annotations "redirect2" }}"
              target:
                kind: KeycloakRealmImport
                name: keycloak-chicken
            - patch: |
                - op: replace
                  path: /spec/realm/clients/4/redirectUris/3
                  # Ensure clients are in expected order before deploying
                  # Targets 5th client (index 4) in realm.clients; index 3 = TPA callback URI
                  value: "{{ index .metadata.annotations "redirect3" }}"
              target:
                kind: KeycloakRealmImport
                name: keycloak-chicken
            - patch: |
                - op: replace
                  path: /spec/realm/clients/4/redirectUris/4
                  # Ensure clients are in expected order before deploying
                  # Targets 5th client (index 4) in realm.clients; index 4 = TPA callback URI with wildcard
                  value: "{{ index .metadata.annotations "redirect4" }}"
              target:
                kind: KeycloakRealmImport
                name: keycloak-chicken
            - patch: |
                - op: replace
                  path: /spec/source/helm/parameters/0/value
                  # Helm parameter 0 = AppDomain (e.g., "tpa.example.com")
                  value: "{{ index .metadata.annotations "AppDomain" }}"
              target:
                kind: Application
                name: trusted-profile-analyzer
            - patch: |
                - op: replace
                  path: /spec/source/helm/parameters/1/value
                  # Helm parameter 1 = OIDCissuer (Keycloak realm issuer URL)
                  value: "{{ index .metadata.annotations "OIDCissuer" }}"
              target:
                kind: Application
                name: trusted-profile-analyzer
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: openshift-gitops
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true

