apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-volume-jfrog-container-registry-artifactory-0
  namespace: artifactory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-jfrog-container-registry-postgresql-0
  namespace: artifactory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
---

