apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: tpa-keycloak
  namespace: tpa-project
  labels:
    app: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  instances: 1
  additionalOptions:
    - name: enable-recovery
      value: "true"
  transaction:
    xaEnabled: true
  adminCredentials: { secretName: keycloak-admin-secret }
  db:
    vendor: postgres
    host: tpa-postgres-primary.tpa-project.svc.cluster.local
    port: 5432
    database: tpa-db
    usernameSecret: { name: postgresql-credentials, key: db.user }
    passwordSecret: { name: postgresql-credentials, key: db.password }
  hostname:
    strict: true
    hostname: tpa-keycloak-tpa-project.apps.rosa.cstt4-ters7-am9.i2pn.p3.openshiftapps.com

  http:
    httpEnabled: true
    ingress:
      enabled: true 
