apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - minio-operator-install.yaml
  - minio-tenant.yaml
  - postgres-keycloak.yaml
  - keycloak-instance.yaml
  - tpa-release.yaml
