apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: tpa-data-bucket-claim
  namespace: tpa-project
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  # ODF StorageClass for S3 access (NooBaa)
  storageClassName: openshift-storage.noobaa.io 
  bucketName: tpa-data-bucket-001
  # The name of the Secret created with the credentials/endpoint (will be created by ODF)
  generateBucketName: tpa-data-bucket

