apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocscluster
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  managedResources:
    cephObjectStores:
      reconcile: true
  storageDeviceSets:
    - name: odf-deviceset
      count: 1
      # Storage devices are created on three nodes (3x replication)
      replica: 3 
      dataPVCTemplate:
        spec:
          # Use the name of an existing StorageClass suitable for ODF
          storageClassName: gp3-ssd 
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 512Gi # Size of the PV for the OSDs
      placement:
        # Optional: Constrain deployment to nodes labeled for storage
        nodeSelector: 
          node-role.kubernetes.io/worker: "" # targets all worker nodes
