apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trusted-profile-analyzer
  namespace: gitops-resources
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: gitops-resources 
  source:
    repoURL: https://charts.openshift.io/
    targetRevision: 1.1.1
    chart: redhat-trusted-profile-analyzer
    helm:
      values: |
        appDomain: "${APP_DOMAIN_URL}"

        ingress:
          className: openshift-default
          additionalAnnotations:
            "haproxy.router.openshift.io/timeout": "5m"

        storage:
          type: s3
          region: http://minio-tpa-storage-hl.tpa-project.svc.cluster.local:9000
          bucket: trustify-tpa-data-001
          accessKey:
            valueFrom: { secretKeyRef: { name: storage-credentials, key: user } }
          secretKey:
            valueFrom: { secretKeyRef: { name: storage-credentials, key: password } }

        database:
          sslMode: require
          host: { valueFrom: { secretKeyRef: { name: postgresql-credentials, key: db.host } } }
          port: { valueFrom: { secretKeyRef: { name: postgresql-credentials, key: db.port } } }
          name: { valueFrom: { secretKeyRef: { name: postgresql-credentials, key: db.name } } }
          username: { valueFrom: { secretKeyRef: { name: postgresql-credentials, key: db.user } } }
          password: { valueFrom: { secretKeyRef: { name: postgresql-credentials, key: db.password } } }

        createDatabase:
          enabled: true
          name: { valueFrom: { secretKeyRef: { name: postgresql-admin-credentials, key: db.name } } }
          username: { valueFrom: { secretKeyRef: { name: postgresql-admin-credentials, key: db.user } } }
          password: { valueFrom: { secretKeyRef: { name: postgresql-admin-credentials, key: db.password } } }

        migrateDatabase:
          enabled: true
          username: { valueFrom: { secretKeyRef: { name: postgresql-admin-credentials, key: db.user } } }
          password: { valueFrom: { secretKeyRef: { name: postgresql-admin-credentials, key: db.password } } }

        oidc:
          issuerUrl: https://keycloak.apps.example.com/auth/realms/tpa-realm
          clients:
            frontend:
              clientId: tpa-frontend
            cli:
              clientId: tpa-cli
              clientSecret:
                valueFrom: { secretKeyRef: { name: oidc-cli, key: client-secret } }
                
        modules:
          createImporters:
            enabled: true
            importers:
              redhat-sboms:
                sbom:
                  description: All Red Hat SBOMs
                  period: 1d
                  source: https://access.redhat.com/security/data/sbom/beta/
                  keys:
                    - https://access.redhat.com/security/data/97f5eac4.txt#77E79ABE93673533ED09EBE2DCE3823597F5EAC4
                  disabled: true
                  fetchRetries: 50
              cve:
                cve:
                  description: CVE list v5
                  period: 1d
                  source: https://github.com/CVEProject/cvelistV5
                  disabled: false
              osv-github:
                osv:
                  description: GitHub Advisory Database
                  period: 1d
                  source: https://github.com/github/advisory-database
                  path: advisories
                  disabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: tpa-project
  syncPolicy:
    automated: { prune: true, selfHeal: true }

