apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trusted-profile-analyzer
  namespace: gitops-resources
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: gitops-resources 
  source:
    repoURL: https://charts.openshift.io/
    targetRevision: 1.1.1
    chart: redhat-trusted-profile-analyzer
    helm:
      parameters:
        - name: appDomain
          value: $(APP_DOMAIN_URL)
        - name: oidc.issuerUrl
          value: $(OIDC_ISSUER_URL)
      values: |
        replicas: 1
        openshift: &tpaOpenShift
          useServiceCa: true
        collector: {}
        ingress:
          className: openshift-default
          additionalAnnotations:
            "haproxy.router.openshift.io/timeout": "5m"

        storage: &tpaStorage
          type: filesystem
          size: 100Gi

        database:
          sslMode: disable
          host:
            valueFrom:
              secretKeyRef:
                name: tpa-pgsql-user
                key: host
          port:
            valueFrom:
              secretKeyRef:
                name: tpa-pgsql-user
                key: port
          name:
            valueFrom:
              secretKeyRef:
                name: tpa-pgsql-user
                key: dbname
          username:
            valueFrom:
              secretKeyRef:
                name: tpa-pgsql-user
                key: user
          password:
            valueFrom:
              secretKeyRef:
                name: tpa-pgsql-user
                key: password

        createDatabase:
          name:
            valueFrom:
              secretKeyRef:
                name: tpa-pgsql-user
                key: dbname
          username:
            valueFrom:
              secretKeyRef:
                name: tpa-pgsql-user
                key: user
          password:
            valueFrom:
              secretKeyRef:
                name: tpa-pgsql-user
                key: password

        migrateDatabase:
          username:
            valueFrom:
              secretKeyRef:
                name: tpa-pgsql-user
                key: user
          password:
            valueFrom:
              secretKeyRef:
                name: tpa-pgsql-user
                key: password

        infrastructure:
          port: 9010

        metrics:
          enabled: false

        oidc: &tpaOIDC
          clients:
            frontend:
              clientId: frontend
            cli:
              clientId: cli
              clientSecret:
                valueFrom:
                  secretKeyRef:
                    name: tpa-realm-chicken-clients
                    key: cli
                
        modules:
          createDatabase:
            enabled: true
          migrateDatabase:
            enabled: true
          createImporters:
            enabled: true
            importers:
              redhat-sboms:
                sbom:
                  description: All Red Hat SBOMs
                  period: 1d
                  source: https://access.redhat.com/security/data/sbom/beta/
                  keys:
                    - https://access.redhat.com/security/data/97f5eac4.txt#77E79ABE93673533ED09EBE2DCE3823597F5EAC4
                  disabled: true
                  fetchRetries: 50
              redhat-csaf:
                csaf:
                  description: All Red Hat CSAF data
                  period: 1d
                  source: redhat.com
                  disabled: true
                  fetchRetries: 50
              cve:
                cve:
                  description: CVE list v5
                  period: 1d
                  source: https://github.com/CVEProject/cvelistV5
                  disabled: false
              osv-github:
                osv:
                  description: GitHub Advisory Database
                  period: 1d
                  source: https://github.com/github/advisory-database
                  path: advisories
                  disabled: false
          server:
            enabled: true
            image: {}
            infrastructure: {}
            ingress: {}
            metrics: {}
            replicas: 1
            resources:
              requests:
                cpu: 1
                memory: 8Gi
            rust: {}
            tracing: {}

        partOf: trustify
        rust:
          logFilter: debug
          backtrace: true
        tls: &tpaTLS
          serviceEnabled: true
          additionalTrustAnchor: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        tracing:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: tssc-tpa
  syncPolicy:
    automated: { prune: true, selfHeal: true }

