#!/bin/bash

set -euo pipefail

# This script generates secret YAML files that can be used with kustomize
# Run this script before deploying to generate all required secrets

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="$SCRIPT_DIR"

# Set namespace variables
TPA_NAMESPACE="tssc-tpa"
KEYCLOAK_NAMESPACE="tssc-keycloak"
REALM="chicken"

# Get INGRESS_URL from the cluster (if available) or use a placeholder
if command -v oc &> /dev/null && oc whoami &> /dev/null 2>&1; then
  INGRESS_URL=$(oc -n openshift-ingress-operator get ingresscontrollers.operator.openshift.io default -o jsonpath='{.status.domain}' 2>/dev/null || echo "PLACEHOLDER.apps.example.com")
else
  INGRESS_URL="PLACEHOLDER.apps.example.com"
fi

# Derive environment-specific values
APP_DOMAIN_URL="-${TPA_NAMESPACE}.${INGRESS_URL}"
KEYCLOAK_HOST="sso.${INGRESS_URL}"
OIDC_ISSUER_URL="https://sso.${INGRESS_URL}/realms/${REALM}"
CYCLONEDX_VER="1.4"

# Generate random passwords
generate_password() {
  local length=${1:-16}
  openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c "$length"
}

generate_uuid_style_password() {
  local random=$(openssl rand -base64 64 | tr -dc 'a-zA-Z0-9' | head -c 32)
  echo "${random:0:8}-${random:8:4}-${random:12:4}-${random:16:4}-${random:20:12}"
}

# Generate passwords
TPA_USER_DB_PASS=$(generate_password 16)
KEYCLOAK_USER_DB_PASS=$(generate_password 16)
SEED_STRING=$(generate_password 16)
PASS_CLI=$(generate_uuid_style_password)
PASS_MANAGER=$(generate_uuid_style_password)
PASS_USER=$(generate_uuid_style_password)

echo "==> Generating secrets for cluster: $INGRESS_URL"

# Generate Secret 1: TPA DB Connection Details
cat > "$OUTPUT_DIR/generated-secret-tpa-db.yaml" <<EOF
# Auto-generated by generate-secrets.sh - DO NOT EDIT MANUALLY
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: tpa-pgsql-user
  namespace: $TPA_NAMESPACE
stringData:
  dbname: tpa
  host: tpa-pgsql.tssc-tpa.svc
  user: tpa
  port: "5432"
  password: "$TPA_USER_DB_PASS"
EOF

# Generate Secret 2: Keycloak DB Connection Details
cat > "$OUTPUT_DIR/generated-secret-keycloak-db.yaml" <<EOF
# Auto-generated by generate-secrets.sh - DO NOT EDIT MANUALLY
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: keycloak-pgsql-user
  namespace: $KEYCLOAK_NAMESPACE
stringData:
  dbname: keycloak
  host: keycloak-pgsql.tssc-keycloak.svc
  user: keycloak
  port: "5432"
  password: "$KEYCLOAK_USER_DB_PASS"
EOF

# Generate Secret 3 & 4: Realm admin secrets
cat > "$OUTPUT_DIR/generated-secret-realm-admin.yaml" <<EOF
# Auto-generated by generate-secrets.sh - DO NOT EDIT MANUALLY
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: keycloak
  namespace: $TPA_NAMESPACE
  name: tpa-realm-chicken-admin
type: Opaque
stringData:
  username: admin
  password: "$SEED_STRING"
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: keycloak
  namespace: $KEYCLOAK_NAMESPACE
  name: tpa-realm-chicken-admin
type: Opaque
stringData:
  username: admin
  password: $SEED_STRING
EOF

# Generate Secret 5 & 6: OIDC Client Secrets
cat > "$OUTPUT_DIR/generated-secret-oidc-clients.yaml" <<EOF
# Auto-generated by generate-secrets.sh - DO NOT EDIT MANUALLY
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: keycloak
  namespace: $TPA_NAMESPACE
  name: tpa-realm-chicken-clients
type: Opaque
stringData:
  cli: "$PASS_CLI"
  testingManager: "$PASS_MANAGER"
  testingUser: "$PASS_USER"
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: keycloak
  namespace: $KEYCLOAK_NAMESPACE
  name: tpa-realm-chicken-clients
type: Opaque
stringData:
  cli: $PASS_CLI
  testingManager: $PASS_MANAGER
  testingUser: $PASS_USER
EOF

# Generate Secret 7: Trustification integration
cat > "$OUTPUT_DIR/generated-secret-trustification.yaml" <<EOF
# Auto-generated by generate-secrets.sh - DO NOT EDIT MANUALLY
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: keycloak
  namespace: $TPA_NAMESPACE
  name: tssc-trustification-integration
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  bombastic_api_url: https://server$APP_DOMAIN_URL
  oidc_issuer_url: https://sso.$INGRESS_URL/realms/$REALM
  oidc_client_id: cli
  oidc_client_secret: $PASS_CLI
  supported_cyclonedx_version: "${CYCLONEDX_VER}"
EOF

# Generate ConfigMap with environment-derived values
cat > "$OUTPUT_DIR/generated-configmap.yaml" <<EOF
# Auto-generated by generate-secrets.sh - DO NOT EDIT MANUALLY
apiVersion: v1
kind: ConfigMap
metadata:
  name: tpa-values-source
  namespace: $TPA_NAMESPACE
data:
  APP_DOMAIN_URL: "$APP_DOMAIN_URL"
  OIDC_ISSUER_URL: "$OIDC_ISSUER_URL"
  KEYCLOAK_HOSTNAME: "$KEYCLOAK_HOST"
  REDIRECT_URI1: "https://server$APP_DOMAIN_URL"
  REDIRECT_URI2: "https://server$APP_DOMAIN_URL/*"
  REDIRECT_URI3: "https://sbom$APP_DOMAIN_URL"
  REDIRECT_URI4: "https://sbom$APP_DOMAIN_URL/*"
EOF

echo "==> Generated files:"
echo "  - generated-secret-tpa-db.yaml"
echo "  - generated-secret-keycloak-db.yaml"
echo "  - generated-secret-realm-admin.yaml"
echo "  - generated-secret-oidc-clients.yaml"
echo "  - generated-secret-trustification.yaml"
echo "  - generated-configmap.yaml"
echo ""
echo "==> Cluster ingress domain: $INGRESS_URL"
echo "==> Generated passwords (save these securely!):"
echo "  TPA DB Password: $TPA_USER_DB_PASS"
echo "  Keycloak DB Password: $KEYCLOAK_USER_DB_PASS"
echo "  Realm Admin Password: $SEED_STRING"
echo "  CLI Client Secret: $PASS_CLI"
echo "  Manager Client Secret: $PASS_MANAGER"
echo "  User Client Secret: $PASS_USER"
