# RBAC resources for the secret generator hook
# These are created in sync-wave 0 (before the hook in wave 1)
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tpa-secret-generator
  namespace: tssc-tpa
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
# Role with permissions to create/update secrets and configmaps in tssc-tpa
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tpa-secret-generator
  namespace: tssc-tpa
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "create", "update", "patch"]
---
# Role with permissions to create/update secrets in tssc-keycloak
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tpa-secret-generator
  namespace: tssc-keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch"]
---
# RoleBinding for TPA namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tpa-secret-generator
  namespace: tssc-tpa
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
  - kind: ServiceAccount
    name: tpa-secret-generator
    namespace: tssc-tpa
roleRef:
  kind: Role
  name: tpa-secret-generator
  apiGroup: rbac.authorization.k8s.io
---
# RoleBinding for Keycloak namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tpa-secret-generator
  namespace: tssc-keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
  - kind: ServiceAccount
    name: tpa-secret-generator
    namespace: tssc-tpa
roleRef:
  kind: Role
  name: tpa-secret-generator
  apiGroup: rbac.authorization.k8s.io
---
# ClusterRole to read IngressController and patch Applications
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tpa-secret-generator-cluster-access
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups: ["operator.openshift.io"]
    resources: ["ingresscontrollers"]
    verbs: ["get", "list"]
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "patch"]
---
# ClusterRoleBinding for cluster-level access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tpa-secret-generator-cluster-access
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
  - kind: ServiceAccount
    name: tpa-secret-generator
    namespace: tssc-tpa
roleRef:
  kind: ClusterRole
  name: tpa-secret-generator-cluster-access
  apiGroup: rbac.authorization.k8s.io
