# RBAC resources for the secret generator PreSync hook
# These must exist before the hook runs, so they're part of the main sync
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tpa-secret-generator
  namespace: tssc-tpa
---
# Role with permissions to create/update secrets and configmaps in tssc-tpa
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tpa-secret-generator
  namespace: tssc-tpa
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "create", "update", "patch"]
---
# Role with permissions to create/update secrets in tssc-keycloak
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tpa-secret-generator
  namespace: tssc-keycloak
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch"]
---
# RoleBinding for TPA namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tpa-secret-generator
  namespace: tssc-tpa
subjects:
  - kind: ServiceAccount
    name: tpa-secret-generator
    namespace: tssc-tpa
roleRef:
  kind: Role
  name: tpa-secret-generator
  apiGroup: rbac.authorization.k8s.io
---
# RoleBinding for Keycloak namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tpa-secret-generator
  namespace: tssc-keycloak
subjects:
  - kind: ServiceAccount
    name: tpa-secret-generator
    namespace: tssc-tpa
roleRef:
  kind: Role
  name: tpa-secret-generator
  apiGroup: rbac.authorization.k8s.io
---
# ClusterRole to read IngressController
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tpa-secret-generator-ingress-reader
rules:
  - apiGroups: ["operator.openshift.io"]
    resources: ["ingresscontrollers"]
    verbs: ["get", "list"]
---
# ClusterRoleBinding for reading IngressController
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tpa-secret-generator-ingress-reader
subjects:
  - kind: ServiceAccount
    name: tpa-secret-generator
    namespace: tssc-tpa
roleRef:
  kind: ClusterRole
  name: tpa-secret-generator-ingress-reader
  apiGroup: rbac.authorization.k8s.io
